# Generated by Django 4.2.6 on 2023-11-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='UploadFile',
        ),
    ]
