# Generated by Django 4.2.7 on 2023-12-21 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_uploadfile_uploadimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadimage",
            old_name="upload",
            new_name="image",
        ),
    ]
