# Generated by Django 5.0 on 2023-12-22 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_rename_upload_uploadimage_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadimage",
            old_name="image",
            new_name="upload",
        ),
    ]
